name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build and Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 